trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

resources:
- repo: self

variables:
- group: version-group
- name: tag
  value: $(Build.BuildId)
- name: projectKey
  value: btshft_Zeus
- name: projectName
  value: Zeus
- name: organization
  value: btshft
- name: connection
  value: sonarcloud

stages:
- stage: Scan
  displayName: Security scan
  jobs:  
  - job: Scan
    displayName: Security scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        hash=${version:0:7}
        echo $hash
        echo "##vso[task.setvariable variable=hash]$hash"
      env: 
        version: $(Build.SourceVersion) 
      displayName: Git Hash 7-digit
    - task: DotNetCoreCLI@2
      displayName: .NET Core - Build
      inputs:
        command: build
        majorVersion: $(majorVersion)
        minorVersion: $(minorVersion)
        patchVersion: $(patchVersion)-preview+$(hash)
        versioningScheme: byPrereleaseNumber
        projects: '$(Build.SourcesDirectory)/src/Zeus.sln'
    - task: WhiteSource Bolt@20
      displayName: WhiteSource Bolt - Analyze