trigger: 
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Run unit tests
      inputs:
        command: test
        projects: '$(Build.SourcesDirectory)/src/Zeus/Zeus.sln'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: btshft/zeus/zeus-bot
        buildContext: "$(Build.SourcesDirectory)/src"
        dockerfile: '$(Build.SourcesDirectory)/src/Zeus/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Login GitHub Package
      inputs:
        command: login
        containerRegistry: github-docker-packages
    - task: Docker@2
      displayName: Push docker image
      inputs:
        command: push
        repository: btshft/zeus/zeus-bot
        containerRegistry: github-docker-packages
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Logout GitHub Package
      condition: always()
      inputs:
        command: logout
        containerRegistry: github-docker-packages