trigger: 
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build docker image
  jobs:  
  - job: Build
    displayName: Build docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Zeus/Dockerfile'
        tags: |
          $(tag)