trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

resources:
- repo: self

variables:
- group: version-group
- name: tag
  value: $(Build.BuildId)
- name: projectKey
  value: btshft_Zeus
- name: projectName
  value: Zeus
- name: organization
  value: btshft
- name: connection
  value: sonarcloud

stages:
- stage: Scan
  displayName: Security scan
  jobs:  
  - job: Scan
    displayName: Security scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarCloudPrepare@1
      displayName: SonarCloud - Prepare
      inputs:
        SonarCloud: $(connection)
        organization: $(organization)
        scannerMode: 'MSBuild'
        projectKey: $(projectKey)
        projectName: $(projectName)
    - task: DotNetCoreCLI@2
      displayName: .NET Core - Build
      inputs:
        command: build
        majorVersion: $(majorVersion)
        minorVersion: $(minorVersion)
        patchVersion: $(patchVersion)-ci+$(Build.SourceVersion)
        versioningScheme: byPrereleaseNumber
        projects: '$(Build.SourcesDirectory)/src/Zeus.sln'
    - task: DotNetCoreCLI@2
      displayName: .NET Core - Test
      inputs:
        command: test
        versionEnvVar: version
        versioningScheme: byEnvVar
        projects: '$(Build.SourcesDirectory)/src/Zeus.sln'
    - task: SonarCloudAnalyze@1
      displayName: SonarCloud - Analyze
    - task: SonarCloudPublish@1
      displayName: SonarCloud - Publish
      inputs:
        pollingTimeoutSec: '300'
