schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  projectKey: 'btshft_Zeus'
  projectName: 'Zeus'
  organization: 'btshft'
  connection: 'sonarcloud'

stages:
- stage: Scan
  displayName: Security scan
  jobs:  
  - job: Scan
    displayName: Security scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarCloudPrepare@1
      displayName: SonarCloud - Prepare
      inputs:
        SonarCloud: $(connection)
        organization: $(organization)
        scannerMode: 'MSBuild'
        projectKey: $(projectKey)
        projectName: $(projectName)
    - task: DotNetCoreCLI@2
      displayName: .NET Core - Build
      inputs:
        command: build
        projects: '$(Build.SourcesDirectory)/src/Zeus.sln'
    - task: DotNetCoreCLI@2
      displayName: .NET Core - Test
      inputs:
        command: test
        projects: '$(Build.SourcesDirectory)/src/Zeus.sln'
    - task: SonarCloudAnalyze@1
      displayName: SonarCloud - Analyze
    - task: SonarCloudPublish@1
      displayName: SonarCloud - Publish
      inputs:
        pollingTimeoutSec: '300'