app:
  environment: Production
  settings:
    bot:
      token: "<bot token>"
      administrators:
        - <admin user id>

    alerting:
      templatesPath: "/app/templates"

image:
  repository: bitshift/zeus
  tag: v0.0.1
  pullPolicy: IfNotPresent

ingress:
  host: zeus.local
  path: /

service:
  type: ClusterIP
  port: 80